import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header/header';
import Navbar from './components/header/navbar/navbar';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'e-shopping with nexyjs13',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">          
      <body className={inter.className}>
          <Header />
          <Navbar /> 
          {children}
        </body>
    </html>
    
  )
}
